config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    post :bid, on: :member
    post :draw, on: :member
  end
  resources :users, only: [:show, :index]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  paginates_per 6
  has_many :users, through: :user_items
  has_many :user_items
  belongs_to :winner, class_name: 'User', foreign_key: :user_id, optional: true
  validates :name, presence: true

  scope :drawn, -> { where.not(winner: nil) }
  scope :undrawn, -> { where(winner: nil) }
  scope :drawable, -> { bidable.where('users_count > 1') }

  def won?
    return true if winner
    false
  end

  def already_bid?(user)
    return true if users.include?(user)
    false
  end

  def bidable?(user)
    return true unless won? || already_bid?(user)
    false
  end

  def drawable?
    return true unless won? || users.count < 2
    false
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :items, through: :user_items
  has_many :user_items
  has_many :won_items, class_name: 'Item', foreign_key: 'user_id'

  after_create :assign_default_role

  def active_bids
    items.where(winner: nil)
  end

  def lost_draws
    Item.drawn.where.not(winner: self) & items
  end

  def admin?
    has_role? :admin
  end

  def ban
    add_role(:banned)
  end

  def make_admin
    add_role(:admin)
  end

  def unban
    remove_role(:banned)
  end

  def remove_admin
    remove_role(:admin)
  end

  private

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :user_id, scope: :item_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  private

  def ensure_current_user_admin?
    return if current_user.roles.pluck(:name).include?('admin')
    flash[:danger] = 'you are not admin'
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :ensure_current_user_admin?, except: [:show, :index, :bid]
  expose(:q) { Item.ransack(params[:q]) }
  expose_decorated(:items) { q.result.page(params[:page]) }
  expose_decorated(:item, build_params: :item_params)

  def create
    if item.save
      flash[:success] = 'Item successfully added'
      redirect_to item
    else
      flash[:danger] = 'Failed to add item'
      render 'new'
    end
  end

  def edit
    if item.users.any?
      flash[:danger] = "can't edit bidded item!"
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if item.users.any?
      flash[:danger] = "can't update bidded item!"
      redirect_back(fallback_location: root_path)
    elsif item.save
      flash[:success] = 'Item successfully updated'
      redirect_to item
    else
      flash[:danger] = 'Failed to update item'
      render 'edit'
    end
  end

  def destroy
    if item.users.empty?
      item.destroy
      redirect_to items_path
      flash[:warning] = 'item successfully destroyed'
    else
      flash[:danger] = "can't destroy bidded item!"
      redirect_back(fallback_location: root_path)
    end
  end

  def bid
    outcome = Bid.run(user: current_user, item: item)
    if outcome.valid?
      flash[:success] = outcome.result
    else
      flash[:danger] = outcome.errors.messages.values.flatten.join(' and ')
    end
    redirect_to item
  end

  def draw
    outcome = Draw.run(item: item)
    if outcome.valid?
      flash[:success] = outcome.result
      DrawMailer.draw_won(item).deliver_now
    else
      flash[:danger] = outcome.errors.messages.values.flatten.join(' and ')
    end
    redirect_to item
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose_decorated(:user, build_params: :user_params)
  # expose(:users) { User.all.page(params[:page]) }

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item_form.html.slim
= simple_form_for item do |f|
  = f.input :name
  = f.submit

app/views/items/edit.html.slim
- provide :header, 'Edit item'
= render 'item_form', submit_message: 'Update!'

app/views/items/index.html.slim
- provide :header, 'Items'
= items.available_items
= link_to 'Add item', new_item_path, class: 'btn btn-primary'
= link_to 'All users', users_path, class: 'btn btn-success'

= search_form_for q do |f|
  = f.label :name_cont
  = f.search_field :name_cont
  = f.submit

- items.each do |item|
  .row: .col-sm-12: .well: .row
    .col-sm-2
      = item.avatar
    .col-sm-6
      = link_to item_path(item) do
        h4 = item.name
    .col-sm-4
      .pull-right
        = render 'shared/lottery_status', item: item

= paginate items

app/views/items/new.html.slim
- provide :header, 'Add item'
= render 'item_form', submit_message: 'Create!'

app/views/items/show.html.slim
- provide :header, 'Item'
.row
  .col-md-10
    h2
      small name:
      =< item.name

    - unless item.winner.nil?
      h2
        small winner:
        =< link_to item.winner.email, user_path(item.winner)
  .col-md-2
    = render'shared/lottery_status', item: item
.row
  .col-md-12
    = item.link_to_draw
    = item.link_to_bid
    = item.link_to_edit
    = item.link_to_destroy

- if item.users.any?
  .row
    .col-md-12
      h3: small bidders:
      ul
      - item.users.each do |user|
        li = link_to user_path(user) do
          = user.name_and_domain

app/views/layouts/_flash_messages.html.slim
- if flash
  - flash.each do |type, message|
    = content_tag :div, class: "alert alert-#{type}" do
      p = message

app/views/layouts/_navigation.html.slim
.row style='padding-top: 70px;'
  .col-md-12
    .navbar.navbar-default.navbar-fixed-top.navbar-inverse
      .container-fluid
        ul.nav.navbar-nav
          li = link_to 'Home', root_path
          li: p.navbar-text = yield(:header)
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li = link_to 'Edit profile', edit_user_registration_path
            li = link_to 'Profile', user_path(current_user)
            li = link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            li = link_to 'Register', new_user_registration_path
            li = link_to 'Log in', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Lottery
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .row
      .col-md-12
        .row
          = render 'layouts/navigation'
        .row
          .col-md-8.col-md-offset-2
            = render 'layouts/flash_messages'
            = yield
    - if ENV['RAILS_ENV']=='development'
      footer
        = debug(params)

app/views/shared/_lottery_status.html.slim
.row
  | won
  = render 'shared/statusicon', result: item.won?
.row
  | bidable
  = render 'shared/statusicon', result: item.bidable?(current_user)
.row
  | drawable
  = render 'shared/statusicon', result: item.drawable?

app/views/shared/_statusicon.html.slim
.pull-right
  - if result == true
    span.glyphicon.glyphicon-ok
  - else
    span.glyphicon.glyphicon-remove

app/views/users/index.html.slim
- provide :header, 'Users'
table.table
 tr
  th = sort_link(@q, :email, 'Email')
  th = sort_link(@q, :items, 'bid items')
  th = sort_link(@q, :won_items, 'won items')
  th = sort_link(@q, :lost_draws, 'lost items')
  - @users.each do |user|
    tr
      td = link_to user.email, user_path(user)
      td = user.items.count
      td = user.won_items.count
      td = user.lost_draws.count

app/views/users/show.html.slim
- provide :header, 'User'
= user.name_and_domain
.row
  .col-md-8: .well
    = image_tag('default', size: '100x100')
    h2.pull-right
      small email:
      = user.email
  .col-md-4: .well
    h4: small roles:
    ul
      - user.roles.each do |role|
        li = role.name

.row
  .col-md-4: .well
    h4: small won items:
    - if user.won_items.any?
      ul
        - user.won_items.each do |item|
          li = link_to item.name, item_path(item)
  .col-md-4: .well
    h4: small waiting for succesful draw:
    - if user.active_bids.any?
      ul
        - user.active_bids.each do |item|
          li = link_to item.name, item_path(item)
  .col-md-4: .well
    h4: small maybe next time:
    - if user.lost_draws.any?
      ul
        - user.lost_draws.each do |item|
          li = link_to item.name, item_path(item)